### ISSUE TITLE
Add Hellmann Worldwide Logistics as adopter

### ISSUE THREAD

**Issue by matzegebbe** [kluctl/www-kluctl.io#104]
### Please provide the name of your company with am optional and very short description of what you do.
For example, "Super Duper Corp, your consultancy buddy"

Hellmann Worldwide Logistics, one of the largest international logistics providers

### Provide an optional URL to link to. The link will be used on the company name and logo.

https://www.hellmann.com/

### Provide an URL to your company logo. It will be part of the adopters list.
Please use a logo that works well on white background (check the existing adopters list).

https://upload.wikimedia.org/wikipedia/commons/e/e0/Logo_Hellmann_Worldwide_Logistics_RGB.jpg

### Please provide a short testimonial describing how and why Kluctl solves something for you.
Check the existing list of adopters for real world examples.

We use Kluctl for configuration management and GitOps, beginning with the management of clusters themselves using ClusterAPI across various cluster environments. These environments are utilized in a broad spectrum of customer and employee-facing products. Kluctl aids us by integrating user-friendly templating, Helm charts, Kustomize, and GitOps with the controller from development through to production. This ensures we maintain oversight and enables us to provide blueprints for teams. Consequently, it plays a crucial role in our internal developer platform.

### What is your name and title at your company? This will be shown in the adopters section.
Example: "John Doe, CTO at Super Duper Corp."

Mathias Gebbe, Team Lead Developer Experience Platform Team at Hellmann Worldwide Logistics

### Optionally describe what your company does and maybe how you found out about Kluctl.
This will not be part of the adopters list, but helps us a lot to understand where adopters come from and why
they ended up using Kluctl.

_No response_

### authorization

- [X] I agree to the statement above.

**Comment by codablock** [comment]
@matzegebbe Thanks. Are you able to reduce the testimonial to something as short as seen in the already existing ones at kluctl.io? I'll also try to reduce it a bit and will in a few minutes provide a suggestion.

**Comment by matzegebbe** [comment]
LGTM!
