### ISSUE TITLE
Adopter - SITA

### ISSUE THREAD

**Issue by rzsita** [kluctl/www-kluctl.io#118]
### Please provide the name of your company with am optional and very short description of what you do.
For example, "Super Duper Corp, your consultancy buddy"

SITA is the world’s leading specialist in air transport communications and information technology.

### Provide an optional URL to link to. The link will be used on the company name and logo.

https://www.sita.aero/

### Provide an URL to your company logo. It will be part of the adopters list.
Please use a logo that works well on white background (check the existing adopters list).

https://www.sita.aero/static/images/logo.svg

### Please provide a short testimonial describing how and why Kluctl solves something for you.
Check the existing list of adopters for real world examples.

Thanks to Kluctl, we successfully transitioned our non-cloud-native applications onto Kubernetes using GitOps. Its templating engine facilitated the creation of essential configurations for our applications.

### What is your name and title at your company? This will be shown in the adopters section.
Example: "John Doe, CTO at Super Duper Corp."

Robert Zeppik, Senior Lead Cloud Engineer at SITA

### Optionally describe what your company does and maybe how you found out about Kluctl.
This will not be part of the adopters list, but helps us a lot to understand where adopters come from and why
they ended up using Kluctl.

We don’t just connect the global aviation industry. We apply decades of experience and expertise to address almost every core business, operational, baggage, and passenger process in air transport.

SITA at Airports:
Solutions and services for airlines, airports, ground handlers operating at the airport spanning operational and business processes, baggage and passenger management.
SITA at Borders:
We ensure that governments can strike a balance between critical security measures, and safer, easier travel.
SITA at Aircraft:
We’re powering a digital shift through our airplane solutions that will reinvent the operations of aircraft, flight, and on-board experience for the benefit of all stakeholders.

Kluctl is at present used in SITA at Airport portfolio to deploy AMS (Airport Management System).

### authorization

- [X] I agree to the statement above.

**Comment by codablock** [comment]
Thanks @rzsita :)
Here is a preview of your entry: https://deploy-preview-119--kluctl.netlify.app/

Are you able to shorten the `SITA is the world’s leading specialist in air transport communications and information technology.` so that it becomes a one-liner?

**Comment by rzsita** [comment]
Hi @codablock,
I shortened it a bit… Is it short enough?

SITA the leading specialist in air transport communications and IT.

**Comment by codablock** [comment]
Better, but still two lines. What about "SITA - leading in air transport communications and IT"?

**Comment by rzsita** [comment]
Sounds good👍🏻
