### ISSUE TITLE
ArgoCD/Flux vs Kluctl - Flux and Push

### ISSUE THREAD

**Issue by rekcah78** [kluctl/www-kluctl.io#136]
```
Push based GitOps is not possible in ArgoCD or Flux, this is however not considered a downside but a strict design choice. At the same time, it would be very hard to implement due the strict reliance on Custom Resources for core features
```

This is wrong for Flux, Reconciliation can be trigger with Webhook Receivers from the git repo or anything.

**Comment by codablock** [comment]
Using Webhooks does not change the nature of how GitOps works in Flux, it's still pull based. To get push based GitOps via Flux, Flux would to implement deployment via the flux CLI that does not involve the controller at all.
