### ISSUE TITLE
Add documentation for kluctl-controller metrics

### ISSUE THREAD

**Issue by AljoschaP** [kluctl/www-kluctl.io#58]
We need to add documentation for the new kluctl-controller metrics. This is a follow-up task for https://github.com/kluctl/flux-kluctl-controller/pull/90.

**Comment by codablock** [comment]
Best is to somehow integrate the documentation into https://github.com/kluctl/flux-kluctl-controller/tree/main/docs and then let the www-kluctl.io sync ([here](https://github.com/kluctl/www-kluctl.io/blob/main/hack/import-kluctl-assets.sh)) handle it.
