### ISSUE TITLE
Adopter - Billrush

### ISSUE THREAD

**Issue by MarkCupitt** [kluctl/www-kluctl.io#61]
### What is the name of your company?

Billrush

### What does your company do and how do you use kluctl?

Bill Rush – From Bill To Bank is a New Zealand fintech start-up established in 2019. The Bill Rush team have been quietly working away for the past three years on developing a next generation customer billing and settlement system that we believe will become a core business technology around which organisations can build better businesses that are more resilient, robust and easier to operate and grow . 

Our Stack is based heavily on Microk8s, primarily using Open Source Technologies. We have two primary Products, our Billing Stack and our Cluster Management Stack. We use Kluctl as a core deployment tool with components that we love being the Helm Integration, Secrets Transformer, Deployment Diffs, flexible Deployment Targets and the Templating with Jinja Vars Substitution.

http://billrush.co.nz
![image](https://user-images.githubusercontent.com/5503184/222856000-ee7aaf54-1630-44f9-9a7e-134722861d21.png)

### URL to your company logo

https://billrush.co.nz/wp-content/uploads/2022/06/cropped-400X100_Bill_Rush-Logo-White-1-1.png

### authorization

- [X] I agree to the statement above.

**Comment by AljoschaP** [comment]
Thank you very much! Do you have a logo in black? Our background is white, unfortunately 🙈

**Comment by MarkCupitt** [comment]
Actually no, Ill see if I can fix taht one for you

Regards

Mark Cupitt

"Never give up .. its the end if you do .. find a way .. dig deep .."
"If we change the world, let it bear the mark of our intelligence"

**Comment by codablock** [comment]
@MarkCupitt We're about to finish the adoptors list design. Do you have an update on the logo?

**Comment by MarkCupitt** [comment]
![bill_rush_cover](https://github.com/kluctl/www-kluctl.io/assets/5503184/49745682-cb90-464e-bf63-af826751d3c8)

https://billrush.co.nz

Size as you see fit

Love the kluctl updates and new features .. we have tossed our bash deployment tools in favor of kluctl ..

**Comment by codablock** [comment]
@MarkCupitt Here is a preview of the adopters section: https://deploy-preview-97--kluctl.netlify.app/

I've also updated the issue template to gather the required info in the future. As some of that was missing in the initial template, I tried to come up with my own stuff in the preview. Please inform me if you are fine with the current version or if you prefer to change something.

**Comment by MarkCupitt** [comment]
Looks great to me .. we actually have kluctl in our ci/cd pipeline now and
expanding on that.
