### ISSUE TITLE
Unaccesible install.sh

### ISSUE THREAD

**Issue by honzarac** [kluctl/www-kluctl.io#83]
### Operating system

N/A

### Browser

N/A

### Bug description

Url for install script from documentation https://kluctl.io/install.sh doesn't serve installation script.

<img width="948" alt="image" src="https://github.com/kluctl/www-kluctl.io/assets/23658575/9d8c87d6-841a-45ab-8379-7987160a4b46">

For the others who experiencing same problem could be temporarily used direct URL: https://raw.githubusercontent.com/kluctl/kluctl/main/install/kluctl.sh

**Comment by codablock** [comment]
Thanks, fixed in #84
