### ISSUE TITLE
Site description is not correct in slack summary

### ISSUE THREAD

**Issue by rsrchboy** [kluctl/www-kluctl.io#88]
### Operating system

Fedora 38

### Browser

Firefox

### Bug description

Pasting the website link into slack shows the following as the summary:

![image](https://github.com/kluctl/www-kluctl.io/assets/59620/5bc334e4-2cd3-4d14-b49c-8c63093644e4)

I'm reasonably sure this is not correct ;)

I took a quick peek through the site config, but couldn't see it set incorrectly anywheres, but figured you may want to be aware of this!

### Steps to reproduce

Paste the link into slack.  (Latest client being used here, FWIW.)

**Comment by hugo-sid** [comment]
Thanks for reporting this issue @rsrchboy. 

@codablock, I noticed this issue elsewhere (not Slack) as well. Feel free to assign this to me.

**Comment by codablock** [comment]
@rsrchboy Thanks for reporting this, didn't notice this yet :)

@hugo-sid sure, go for it :+1:
