### ISSUE TITLE
No fallback fonts specified - site uses serif fonts on some devices

### ISSUE THREAD

**Issue by netthier** [kluctl/www-kluctl.io#94]
### Operating system

NixOS 23.11

### Browser

Firefox 122.0

### Bug description

The website exclusively renders using serif fonts, which looks weird.
![image](https://github.com/kluctl/www-kluctl.io/assets/66856670/155d3d59-e3b6-4c40-9f29-cffd79ac37e6)
A closer inspection of the CSS values reveals that a specific list of fonts without a fallback is being used, and I have none of the fonts:
![image](https://github.com/kluctl/www-kluctl.io/assets/66856670/ed5809d6-5568-45e2-b792-26844321b8ed)

### Steps to reproduce

Open the website on a device without any of the fonts specified in the CSS.

**Comment by codablock** [comment]
This was fixed in b8256a8397e79ef94586d3c03c6a2c6e9a3297fe
